namespace Verification.help_form
{
    internal enum TreeTags { GENERAL, PROGRAM, VER1, VER2, VER_PACK, MISTAKES, AD_MISTAKES, CD_MISTAKES, UCD_MISTAKES, METRICS, AD_METRICS, CD_METRICS, UCD_METRICS };
}
